# Numpy for ZakaEgy.Fit


In [2]:
import numpy as np ## Importing Numpy

array1 = np.array([0, 1, 2, 3, 4]) # Creating array
array1

array([0, 1, 2, 3, 4])

In [3]:
array1.shape # Array Shape

(5,)

In [4]:
array2 = np.arange(10) # Ranged array with step 1 by default
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,30,2) # Ranged array with step 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [6]:
np.zeros(5) # vector of zeros

array([0., 0., 0., 0., 0.])

#  Multiple Dimension array

In [7]:
np.zeros((5,5)) # 5 x 5 Zeros Vector

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((5,5)) # 5 x 5 ones Vector

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
np.full((5,5),6) #Full Vector of number 6 with dimension 10 x 1

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [10]:
np.full((10,10),6) #Full Vector of number 6 with dimension 10 x 10

array([[6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6]])

## Converting List to numpy

In [11]:
example = [1,2,3,4,5,6,7]
np.array(example)

array([1, 2, 3, 4, 5, 6, 7])

# # Accessing element in numpy

In [12]:
np2 = np.array(example)
np2[5]

6

# Slicing Numpy

In [13]:
np2[1:5] # Without Steps

array([2, 3, 4, 5])

In [14]:
np2[1:6:2] # With Step 2

array([2, 4, 6])

In [15]:
np2[2:] # Slice from element 3 to end

array([3, 4, 5, 6, 7])

In [16]:
np2[-5:-1] # Slicing from last 

array([3, 4, 5, 6])

In [17]:
np2[::2] # From start to end with step 2

array([1, 3, 5, 7])

## 2D Slicing

In [18]:
example2 = [8,9,10,11,12,13,14]
np3 = np.array([example,example2])
np3

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
np3[:,2:5] ## [row,column] slicing as 1D but with 2D

array([[ 3,  4,  5],
       [10, 11, 12]])

In [20]:
np3.shape ## matrix of 2 x 7 

(2, 7)

## Universal Function of Numpy

In [21]:
np.sqrt(np2) ## Return Square root of each element

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131])

In [22]:
np4 = np.array([-1,-3,-5,9,5,6,-7])
np4

array([-1, -3, -5,  9,  5,  6, -7])

In [23]:
np.absolute(np4) ## Return the absolute of number ( -ve --> ve )

array([1, 3, 5, 9, 5, 6, 7])

In [24]:
np.exp(np4) ## e^(each element of List)

array([3.67879441e-01, 4.97870684e-02, 6.73794700e-03, 8.10308393e+03,
       1.48413159e+02, 4.03428793e+02, 9.11881966e-04])

In [25]:
np.max(np4) ## Return Maximum of list

9

In [26]:
np.min(np4) ## Return Minimum of list

-7

In [27]:
np.sign(np4) ## Return the sign of each ( -1 --> -ve , 1 --> +ve )

array([-1, -1, -1,  1,  1,  1, -1])

In [28]:
np.sin(np4) ## sin(Each element of list)

array([-0.84147098, -0.14112001,  0.95892427,  0.41211849, -0.95892427,
       -0.2794155 , -0.6569866 ])

In [29]:
np.cos(np4) ## cos(Each element of list)

array([ 0.54030231, -0.9899925 ,  0.28366219, -0.91113026,  0.28366219,
        0.96017029,  0.75390225])

In [30]:
np.tan(np4) ## tan(Each element of list)

array([-1.55740772,  0.14254654,  3.38051501, -0.45231566, -3.38051501,
       -0.29100619, -0.87144798])

In [31]:
np.log(np2) ## Return the log of element ( if -ve value return nan, if zero return inf ( Infinity ))

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015])

## Copy vs View 

In [32]:
np5 = np4.view() # Copy the array and still connected to the original array
np5[5] = 10 ## Affect on the copied and the original array
np5

array([-1, -3, -5,  9,  5, 10, -7])

In [33]:
np4

array([-1, -3, -5,  9,  5, 10, -7])

In [34]:
np6 = np4.copy() # copy the array in another array withot affecting on the original one
np6[5] = 50  ## Does not Affect on the original array
np6

array([-1, -3, -5,  9,  5, 50, -7])

In [35]:
np4

array([-1, -3, -5,  9,  5, 10, -7])

## Shape & Reshape


In [36]:
np2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) ## Will be used
np2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np3 = np.array([[ 1,  2,  3,  4,  5,  6],
             [ 7,  8, 9, 10, 11, 12]]) ## Will be used
np3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [38]:
np2.shape # Get Shape

(10,)

In [39]:
np3.shape # Get Shape

(2, 6)

In [40]:
## Reshape 1D Array
np2.reshape(2,5)  # reshape(row,col)  --> row x col of the new shape == row x col of the old shape

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
np3.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
np3.reshape(-1) ## Flat the 2D to 1D

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Iteration using numpy

In [43]:
for x in np2:
    print(x)

0
1
2
3
4
5
6
7
8
9


In [44]:
for x in np3:
    # print(x) --> print each row lonely
    for y in x:
        ## Print Individual element in 2D Array
        print(y)  
    

1
2
3
4
5
6
7
8
9
10
11
12


In [45]:
np7 = np3.reshape(2,2,3)
np7

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [46]:
for x in np7:
    ## print(x) 
    for y in x:
        ## print(y)
        for z in y:
            print(z) ## Print Individual element in 3D Array

1
2
3
4
5
6
7
8
9
10
11
12


In [47]:
for x in np.nditer(np3):
    print(x) # print Individual element in n-D Array ( instead of using many loops )

1
2
3
4
5
6
7
8
9
10
11
12


## Sorting

In [48]:
np9 = np.array([-9,8,7,0,25,3,6,98,-11,-99,3,20,3])
np9

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3])

In [49]:
np.sort(np9,axis = 0) 

array([-99, -11,  -9,   0,   3,   3,   3,   6,   7,   8,  20,  25,  98])

In [50]:
from numpy import doc

In [51]:
help(np.sort) # Retrun more details about the needed function such as sort as shown

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si

## Search

In [52]:
np.where(np9 == 3) # return the index of the needed number where i put to search ( np.where(array == needed number)) 

(array([ 5, 10, 12], dtype=int64),)

In [53]:
np9[np.where(np9 == 3)]

array([3, 3, 3])

In [54]:
np.where(np9 % 2 == 0) # Return the even number index

(array([ 1,  3,  6,  7, 11], dtype=int64),)

In [55]:
np9[np.where(np9 % 2 == 0)] # Return the even number 

array([ 8,  0,  6, 98, 20])

## Filtering Array

In [56]:
np9

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3])

In [57]:
filtered = []
for thing in np9:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
np.array(filtered) # Filter the Array depending on the condition 

array([False,  True, False,  True, False, False,  True,  True, False,
       False, False,  True, False])

In [58]:
# Easy way to filter using Numpy

filtered = np9 % 2 == 0
filtered

array([False,  True, False,  True, False, False,  True,  True, False,
       False, False,  True, False])

# More Topics From Kaggle NoteBook

### Deal With file

In [59]:
np.save("Test",np9) ## Save Data in File

In [60]:
np.load('Test.npy') ## Load Data from File

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3])

## More Topics

In [61]:
# Diagonal Matrix
# 5 x 5 diagonal matrix that contains the numbers 10,20,30, and 50 on its main diagonal
np10 = np.diag([10,20,30,50,60]) ## N x N Matrix N == Number of element in diag
np10

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 50,  0],
       [ 0,  0,  0,  0, 60]])

In [62]:
np.linspace(0,25,5)

array([ 0.  ,  6.25, 12.5 , 18.75, 25.  ])

In [63]:
np10.ndim # Return the Dimension of Matrix ( 2D )

2

In [64]:
np10.dtype # Return the DataType of Matrix 

dtype('int32')

In [65]:
np.array([1,2,3,4,5], dtype = 'int16') ## to reduce the memory usage

array([1, 2, 3, 4, 5], dtype=int16)

In [66]:
np10.itemsize # Return the size of an element in array

4

In [67]:
np10.size # Return Number of elements

25

In [68]:
np10.nbytes # Return the used Bytes for all array

100

In [69]:
np10[3,3] = 99 ## access and change specific element in array
np10

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 99,  0],
       [ 0,  0,  0,  0, 60]])

In [70]:
np3[0,:] # Print Specific Row

array([1, 2, 3, 4, 5, 6])

In [71]:
np3[:,1] # Print Specific Column

array([2, 8])

In [72]:
np.full_like(np10,10) # full all elements in np10 with 10 only 

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [73]:
np.random.randn(10) # Generate vector of random numbers

array([ 0.50741901, -1.92064735, -0.01124758,  0.16366047,  0.14212694,
       -0.91465657, -0.0525759 ,  1.65671206,  0.01877534, -1.42375364])

In [74]:
np.random.randn(5,5) # Generate matrix of random numbers of size 5 x 5

array([[-0.40965803,  2.6904307 , -0.03537505, -0.69227521, -1.57009302],
       [ 0.27910862, -0.2244695 ,  1.70226088, -0.8535106 , -0.32479792],
       [ 0.46924723, -0.8240636 , -0.14113633, -0.8635666 ,  0.86679816],
       [-1.32228899,  0.38423659, -0.89222837, -0.33307347, -0.628176  ],
       [ 0.37371138, -1.68859986, -0.29594988, -1.13903339, -0.22180605]])

In [75]:
np.random.random_sample(np2.shape) # Generate matrix of random numbers from 0 to 1 of size of np2

array([0.09931254, 0.17311146, 0.03822009, 0.52807812, 0.72057052,
       0.91949354, 0.21851587, 0.20112744, 0.69771599, 0.63056257])

In [76]:
np.random.randint(10,size = (5,5)) # Generate matrix of random numbers from 0 to 10 of size of 5 x 5
# randint(maximum_number_to_reach , size = (row, column))

array([[8, 4, 0, 4, 3],
       [4, 5, 1, 5, 7],
       [2, 8, 8, 0, 1],
       [2, 7, 5, 6, 1],
       [2, 9, 3, 5, 6]])

In [77]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [78]:
np.repeat(arr,2) # repeat each element twice

array([1, 1, 2, 2, 3, 3, 4, 4])

In [79]:
np.sin(arr) # Return Sine of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [80]:
np.cos(arr) # Return Cosine of each element

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [81]:
np.tan(arr) # Return Tan of each element

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

In [82]:
np.log(arr) # Return Log of each element

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [83]:
np2 = np.arange(8)
np2 = np2.reshape(4,2)
np2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [84]:
np1 = np.arange(8,16)
np1 = np1.reshape(2,4)
np1

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [85]:
np.matmul(np1,np2) # multiple between to matrix ( Cross Product )

array([[124, 162],
       [172, 226]])

In [86]:
np.linalg.det(np10) # Find the determate of the matrix

35640000.00000002

In [87]:
np.max(np10) # Return Maximum Number

99

In [88]:
np.min(np10) # Return Minimum Number

0

In [89]:
np2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [90]:
np.delete(np2,[1,4,5]) ## Delete the exist in the index of the given

array([0, 2, 3, 6, 7])

In [91]:
np9

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3])

In [92]:
np.append(np9,[111,10,12,69,62,0,0,0,0,0,0,0,6], axis = 0) ## Add a new element in the array in new Row

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3,
       111,  10,  12,  69,  62,   0,   0,   0,   0,   0,   0,   0,   6])

In [93]:
np10

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 99,  0],
       [ 0,  0,  0,  0, 60]])

In [94]:
np.append(np10, [[10], [15], [0] ,[0] ,[0]], axis = 1) ## Add a new element in the array in new Column

array([[10,  0,  0,  0,  0, 10],
       [ 0, 20,  0,  0,  0, 15],
       [ 0,  0, 30,  0,  0,  0],
       [ 0,  0,  0, 99,  0,  0],
       [ 0,  0,  0,  0, 60,  0]])

In [95]:
x = np.array([1,2])
x

array([1, 2])

In [96]:
Y = np.array([[3,4],[5,6]])
Y

array([[3, 4],
       [5, 6]])

In [97]:
z = np.vstack((x,Y)) # [[1,2], [3,4], [5,6]]
z

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
w = np.hstack((Y,x.reshape(2,1))) # [[3,4,1], [5,6,2]]
w

array([[3, 4, 1],
       [5, 6, 2]])

In [99]:
np.diag([1,2,3,4], k = -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [100]:
np.diag([1,2,3,4], k = 1)

array([[0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4],
       [0, 0, 0, 0, 0]])

In [101]:
np10

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 99,  0],
       [ 0,  0,  0,  0, 60]])

In [102]:
np10[np10 > 70] = 50
np10

array([[10,  0,  0,  0,  0],
       [ 0, 20,  0,  0,  0],
       [ 0,  0, 30,  0,  0],
       [ 0,  0,  0, 50,  0],
       [ 0,  0,  0,  0, 60]])

In [103]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

## Math and Algebra

In [104]:
x

array([1, 2, 3, 4, 5])

In [105]:
y

array([6, 7, 2, 8, 4])

In [106]:
np.intersect1d(x,y) # Return the intersection between the 2 arrays 


array([2, 4])

In [107]:
np.setdiff1d(x,y) # Return the elements exist in x and does not exist in y

array([1, 3, 5])

In [108]:
np.setdiff1d(y,x) # Return the elements exist in y and does not exist in x

array([6, 7, 8])

In [109]:
np.union1d(x,y) # Return the union of the 2 arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [110]:
np9

array([ -9,   8,   7,   0,  25,   3,   6,  98, -11, -99,   3,  20,   3])

In [111]:
np.add(x,y)

array([ 7,  9,  5, 12,  9])

In [112]:
np.subtract(y,x)

array([ 5,  5, -1,  4, -1])

In [113]:
np.multiply(x,y)

array([ 6, 14,  6, 32, 20])

In [114]:
np.divide(x,y)

array([0.16666667, 0.28571429, 1.5       , 0.5       , 1.25      ])

In [115]:
np.sqrt(y)

array([2.44948974, 2.64575131, 1.41421356, 2.82842712, 2.        ])

In [116]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [117]:
np.power(x,2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [118]:
4*x

array([ 4,  8, 12, 16, 20])

In [119]:
4+x

array([5, 6, 7, 8, 9])

In [120]:
4/x

array([4.        , 2.        , 1.33333333, 1.        , 0.8       ])

## Statistical Functions

In [121]:
x.mean() # Average of all elements

3.0

In [122]:
np2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [123]:
np2.mean(axis = 0) # Average of all elements in the columns

array([3., 4.])

In [124]:
np2.mean(axis = 1) # Average of all elements in the Rows

array([0.5, 2.5, 4.5, 6.5])

In [125]:
x.std() # Return the standard deviation

1.4142135623730951

In [126]:
x.sum() # Return the sum od array

15

In [127]:
x.min() # Return the minimum of the array

1

In [128]:
x.max() # Return the maximum of the array

5

In [129]:
np.median(x) # Retruns Median of all elements

3.0

## Extra Funcionallity

In [130]:
np.deg2rad(x) # Turn the degree to be rad ( 30 --> pi/6 )

array([0.01745329, 0.03490659, 0.05235988, 0.06981317, 0.08726646])

In [140]:
np.empty((5,3)) ## Matrix of zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [151]:
np12 =np.random.uniform(low = 4, high = 15, size = (3,3)) # Uniformally Distributed Random Numbers
np12

array([[ 9.5979619 , 11.7543713 ,  9.14371765],
       [10.36672974,  7.88988679,  7.43090766],
       [12.02138059, 12.8590151 , 12.84255371]])